apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-website-1
  labels:
    app: static-website-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-website-1
  template:
    metadata:
      labels:
        app: static-website-1
    spec:
      containers:
      - name: static-website-1
        image: amit894/static-website-1:1.0.0
        ports:
        - containerPort: 80
